addons:
  apt:
    packages:
    - rsync
    - sshpass
sudo: true
dist: trusty
node_js: "stable"
install: npm install
branches:
  only:
  - master
  - release
script: npm run build
after_success:
  - rsync -chavzP --rsh="sshpass -e ssh -l $SSH_USERNAME" * $SSH_USERNAME@ituk.ee:/var/ituk.ee/build
