name: Deploy to ituk.ee

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ituk.ee

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'

    - name: Install dependencies
      run: npm install --force

    - name: Decrypt deploy key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to ituk.ee
      run: |
        rsync -chavzP --rsh="ssh -l $SSH_USERNAME" build/* $SSH_USERNAME@ituk.ee:/var/ituk.ee/build
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
