name: Deploy to ituk.ee

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'

    - name: Install dependencies
      run: npm install --force
        
    - name: Deploy to ituk.ee
      run: |
        rsync -chavzP --rsh="ssh -l $SSH_USERNAME"  build/*  -p27008 $SSH_USERNAME@esport.pld.ttu.ee:/home/ityk/ituk.ee/build
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
