name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.13.1' # Adjust to the appropriate Node.js version
    - name: Install dependencies
      run: npm install --force

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOY_RSA }}
        known_hosts: unnecessary

    - name: Adding Known Hosts
      run: ssh-keyscan -H ituk.ee >> ~/.ssh/known_hosts
    - name: Build
      run: docker build -t nextjs-ituk-ee .
    - name: Push
      run: docker save nextjs-ituk-ee | ssh -C deploy@ituk.ee docker load
    - name: Deploy
      run: ssh deploy@ituk.ee "docker rm $(docker stop $(docker ps -a -q --filter ancestor=nextjs-ituk-ee --format="{{.ID}}")) && docker run -d -p 6969:6969 nextjs-ituk-ee"
    - name: Cleanup SSH keys
      run: rm ~/.ssh/id_rsa
