name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Decrypt deploy key
        run: |
          openssl aes-256-cbc -K ${{ secrets.DEPLOY_KEY_K }} -iv ${{ secrets.DEPLOY_KEY_IV }} -in deploy_rsa.enc -out deploy_rsa -d
          chmod 600 deploy_rsa
          eval "$(ssh-agent -s)"
          ssh-add deploy_rsa
      - name: Build project
        run: npm run build

      - name: Deploy to remote server
        uses: easingthemes/ssh-deploy@v2
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          args: -chavzP
          local-dir: _work/ituk.ee/*
          remote-dir: /var/ituk.ee/build
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          
      - name: Build project
        run: npm run build
