name: Node.js CI

on:
  push:
    branches:
      - master

env:
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'
    - name: Install dependencies
      run: npm install --force
    - name: Build
      run: npm run build -prod
    - name: Deploy
      run: rsync -chavzP --rsh="ssh -l deploy" build/* deploy@ituk.ee:/var/ituk.ee/build
      env:
        ssh-private-key: ${{ secrets.DEPLOY_RSA }}
